#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: 363 Final Report: Stroop test
#+author: Andrej Glavic, Yuanxi Liu 20688855, Rachel Morton 20925026, Wasam Syed 20746474, Amy Wang
#+email: r3morton@uwaterloo.ca
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 26.3 (Org mode 9.2.6)
#+latex_class: article
#+latex_class_options:
#+latex_header: \bibliographystyle{plain}
#+latex_header_extra:
#+description:
#+keywords:
#+subtitle:
#+latex_compiler: pdflatex
#+date: \today

** Introduction
John Ridley Stroop published the groundbreaking, "Studies of interference in serial verbal ractions" in the Journal of Experimental Psychology in 1935 \cite{Stroop1935}. Ever since, psychology students worldwide learn about the "Stroop effect", where incongruent stimuli take longer to process than do congruent stimuli. Even though Stroop wasn't the first to publish this effect, his experiments were foundational; his original study is one of the most-cited papers in the history of experimental psychology \cite{MacLeod1991Stroop}.

In one part of Stroop's classic study, participants had to say the ink colour of the printed word rather than read the word. For instance, if the word 'RED' was printed in purple ink, they were to say, "purple" and not "red". Stroop noticed that subjects took significantly longer to complete this colour naming task than one where they just had to name the colour of coloured squares. This difference in response time, or processing speed, is what is known as the Stroop effect.

** Methods
There have been many variations on Stroop's experiment over the years. Since key presses are easier to time than a person reading aloud, we chose to go with a "manual" Stroop task where reaction time is measured by how long it takes a participant to press a certain key on a keyboard after being shown the stimuli on the computer screen. We used the psychopy library in python to program the experiment \cite{Peirce2019Psychopy} and followed the example shown in the demo Stroop task at psytoolkit.org \cite{PsytoolkitStroopDemo}. 

Computational tools used? R??

** Results

*** 1. Collect data into a dataframe:

#+BEGIN_SRC python :results output :session *StroopData*
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt

files = os.listdir()

# Identify all csv files in the directory
csv_files = []
for file in files:
    if file[-4:] == ".csv":
        csv_files.append(file)
data = pd.DataFrame()
for file in csv_files:
    data = data.append(pd.read_csv(file))

pd.set_option('display.max_rows', None)
print(data)
#+END_SRC

#+RESULTS:
#+begin_example
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
Word Ink  Response Time  Correct
0     g   b       0.902731      1.0
1     g   g       0.757359      1.0
2     b   y       0.914164      1.0
3     r   b       0.928025      1.0
4     b   b       0.566040      1.0
..  ...  ..            ...      ...
15    r   y       1.873278      1.0
16    y   y       1.865308      1.0
17    y   r       1.841314      1.0
18    b   b       1.498685      1.0
19    y   y       2.081316      1.0

[179 rows x 4 columns]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pandas_read_csv.py'; 'pandas_read_csv' is not a package
#+end_example


*** Descriptive statistics
[##] participants completed [##] trials.

#+BEGIN_SRC python :session *StroopData* :exports both :results output
data.mean()
#+END_SRC

#+RESULTS:
: Traceback (most recent call last):
:   File "<stdin>", line 1, in <module>
: NameError: name 'data' is not defined


[Include code]

Congruent trials are where the colour word and the font colour match. Incongruent trials are where the font colour is different than the colour word.


We calculated the Stroop effect as the average response time for correct, incongruent trials minus correct, congruent trials.

[t-test comparing the means of (correct) congruent vs (correct) incongruent trials.]

[PLOT]

** Discussion and Conclusions
 
Our experiment takes less than two minutes to complete. It requires pressing the appropriate keyboard key rather than naming the colour aloud as Stroop did originally \cite{Stroop1935}. In our test, there are only 20 trials and a handful [##?] of participants. For a more reliable measure of the Stroop effect you would want to have considerably more participants along with more trials.

** References

#+latex: \bibliography{finalReportBib}

